void ppinteractiongamma();
void ppinteractiongammakelner();
double Fgamma(double x, double Ep);
double PPCrossSection(double Ep);
double Felectron(double x, double Ep) ;
double Fneutrino(double x, double Ep) ;
void ppinteractiondirac();
double interpolationprotonflux(double protonenergy);
double pionXS(double Ep);
double averagepionmultiplicity(double Tp);
double getAmax(double Ep);
double mu(double  Tp);
double kappa(double Tp);
double newFgamma(double Egamma,double Ep);
